import React, { FC, ReactNode } from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '../Navbar'
import styles from "./MainLayout.module.css";

type BoxProps = {
  children: ReactNode; // 👈️ added type for children
};

const inter = Inter({ subsets: ['latin'] })

export const MainLayout: FC<BoxProps> = ({children}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />

      <main className={`${styles.main} ${inter.className}`}>
        {children}
      </main>
    </div>
    )
}

